export const isFirefox = process.env.BROWSER === 'firefox'
export const isEdge = process.env.BROWSER === 'edge'

export const action = isFirefox ? chrome.browserAction : chrome.action

export const mainUrl = '1vpn.org'
export const backupUrls = ['1vpn.co', 'onevpn.com', 'cloudlogcdn.com']
export const proxyAuthUrl = 'cloudflaircdn.com'

export const androidUrl =
  'https://play.google.com/store/apps/details?id=com.one.vpnapp' +
  `&hl=${chrome.i18n.getUILanguage()}`

export const freeCredentials = {
  username: 'a2epfq5ugq0u',
  password: 'ptkx3fqg6v7n',
}

export const ONE_HOUR = 60 * 60 * 1000
export const TWELVE_HOURS = 12 * 60 * 60 * 1000
export const TWENTY_FOUR_HOURS = 24 * 60 * 60 * 1000
export const TWO_MINUTES = 2 * 60 * 1000
export const FORTY_EIGHT_HOURS = 48 * 60 * 60 * 1000
export const FIVE_DAYS = 5 * 24 * 60 * 60 * 1000
export const SEVENTY_TWO_HOURS = 72 * 60 * 60 * 1000

export const errorCodes = { invalidToken: 1001 }

export const reviewUrl =
  (isFirefox
    ? 'https://addons.mozilla.org/firefox/addon/1vpn/reviews'
    : isEdge
    ? 'https://microsoftedge.microsoft.com/addons/detail/dalhgafbhpdolibignjckpmiejgfddjp'
    : 'https://chromewebstore.google.com/detail/akcocjjpkmlniicdeemdceeajlmoabhg/reviews') +
  `?hl=${chrome.i18n.getUILanguage()}`

export const localeMessageKeys = [
  'upgrade',
  'signUp',
  'login',
  'continueText',
  'username',
  'password',
  'twoFaToken',
  'loginEnterEmailAndPassword',
  'loginInvalidCredentials',
  'loginTwoFaRequired',
  'loginCouldNotReachServers',
  'loginInvalidOrMissingTwoFaToken',
  'loginInvalidResponseFromServer',
  'loginCouldNotLoadAccount',
  'loginNetworkError',
  'loading',
  'resetPassword',
  'primaryApiBlockedPart1',
  'primaryApiBlockedPart2',
  'connected',
  'disconnected',
  'goToOptionsPage',
  'goToLocationsPage',
  'upgradeText1',
  'upgradeText2',
  'menu',
  'account',
  'options',
  'contactUs',
  'email',
  'plan',
  'premium',
  'free',
  'editInfo',
  'logout',
  'spoofGeolocation',
  'disableWebRtc',
  'spoofGeolocationSubTitle',
  'disableWebRtcSubTitle',
  'locations',
  'reviewModalTitle',
  'reviewModalButton',
  'shareModalTitle',
  'shareText',
  'x',
  'facebook',
  'linkedin',
  'vk',
  'ok',
  'telegram',
  'upgradeLocation',
  'installSuccess',
  'installInstructions',
  'tryOurAndroidApp',
  'scanQrCodeOrClickButton',
  'scanOrClickQRCode',
  'downloadApp',
  'save33Percent',
  'deal',
  'january',
  'february',
  'march',
  'april',
  'may',
  'june',
  'july',
  'august',
  'september',
  'october',
  'november',
  'december',
  'upgradeModalText',
  'claimOffer',
  'until',
  'save33OnPremiumUntil',
  'save33OnPremium',
  'installModalText',
  'copyLink',
  'linkCopied',
  'getAndroidApp',
  'referToUnlock',
  'toUnlockThisLocation',
  'installAndroidToUnlock',
  'upgradeToPremium',
  'moreLocationsAndFasterSpeeds',
  'tryAndroidApp',
  'get1VPNForAndroid',
  'reviewToUnlock',
  'leaveReviewToUnlock',
  'continueFree',
  'getPremium',
  'unlockAllServerLocations',
  'accessServersWorldwide',
  'fastestSpeeds',
  'consistentAndFastInternetSpeeds',
  'tenDayMoneyBackGuarantee',
  'fullRefundIfNotSatisfied',
  'chooseYourPlan',
  'unlockAllFeaturesWithPremium',
  'rateYourExperience',
  'rateUsMessage',
  'blockedServersModalTitle',
  'blockedServersModalButton',
  'au',
  'br',
  'ca',
  'cl',
  'fr',
  'de',
  'il',
  'in',
  'jp',
  'kr',
  'mx',
  'nl',
  'pl',
  'ro',
  'sg',
  'es',
  'se',
  'uk',
  'use',
  'uss',
  'usw',
  'ue',
  'us',
  'uw',
  'za',
  'syd',
  'sao',
  'yto',
  'cdg',
  'fra',
  'bom',
  'nrt',
  'mex',
  'ams',
  'sgp',
  'mad',
  'sto',
  'lhr',
  'ewr',
  'lax',
  'scl',
  'jnb',
  'icn',
  'waw',
  'atl',
  'blr',
  'del',
  'dfw',
  'hnl',
  'itm',
  'man',
  'mel',
  'mia',
  'ord',
  'sea',
  'sjc',
  'tlv',
]
