export const theme = {
  colors: {
    // transparent: 'transparent',
    // black: '#1f1f1f',
    // blue: '#106CD5',
    // darkBlue: '#035ABE',
    // grey: '#e7eaed',
    // darkGrey: '#c4cbd3',
    // grey: '#808080',
    // backgroundGrey: '#f0f4f9',
    // white: '#fff',

    transparent: 'transparent',
    white: '#fff',
    white20: 'rgba(255, 255, 255, 0.2)',
    black: '#000',
    blue: '#106CD5',
    blue10: 'rgba(16, 108, 213, 0.1)',
    darkBlue: '#035ABE',
    grey: '#717182',
    borderGrey: '#e5e5e5',
    borderGrey50: 'rgba(229, 229, 229, 0.5)',
    darkBorderGrey: '#dcdcdc',
    toggleGrey: '#cbd5e1',
    bgGrey: '#f9f9fa',
    green: '#00c950',
    lightGreen: '#f0fdf4',
    red: '#eb3b5a',
    yellow: '#fed330',
  },
  link: {
    color: 'black',
    textDecoration: 'none',
    '&:hover': {
      color: 'darkBlue',
    },
  },
  forms: {
    input: {
      width: '100%',
      fontSize: '14px',
      fontWeight: 300,
      height: '48px',
      px: '16px',
      border: '1px solid',
      borderColor: 'borderGrey',
      borderRadius: '8px',
      transition: 'border-color 0.2s ease-in-out',
      '&::placeholder': {
        fontWeight: 300,
        color: 'grey',
      },
      ':focus': {
        outline: 'none',
        boxShadow: '0 0 0 0',
        borderColor: 'blue',
      },
      ':hover': {
        borderColor: 'blue',
      },
    },
    select: {
      cursor: 'pointer',
      borderRadius: '8px',
      background: 'transparent',
      border: '1px solid',
      borderColor: 'borderGrey',
      width: '100%',
      outline: 'none',
      py: '6px',
      pl: '12px',
      pr: '32px',
      ':hover': {
        borderColor: 'blue',
      },
    },
  },
  styles: {
    baseButton: {
      width: '100%',
      minHeight: '42px',
      display: 'flex',
      boxSizing: 'border-box',
      cursor: 'pointer',
      alignItems: 'center',
      justifyContent: 'center',
      textDecoration: 'none',
      transition: 'all 0.2s ease-in-out',
      borderRadius: '8px',
      py: '10px',
      px: '8px',
      color: 'white',
      bg: 'blue',
      ':hover': {
        bg: 'darkBlue',
      },
      whiteSpace: 'nowrap',
      overflow: 'hidden',
    },
    outlineButton: {
      width: '100%',
      minHeight: '42px',
      display: 'flex',
      boxSizing: 'border-box',
      cursor: 'pointer',
      alignItems: 'center',
      justifyContent: 'center',
      textDecoration: 'none',
      transition: 'all 0.2s ease-in-out',
      borderRadius: '8px',
      py: '10px',
      px: '8px',
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      bg: 'white',
      color: 'black',
      border: '1px solid',
      borderColor: 'darkBorderGrey',
      ':hover': {
        bg: 'borderGrey50',
      },
    },
  },
}
